const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info: {
      title: 'My test API',
      secription: 'API documentation generated by swagger-autogen'
    },
    host: 'localhost:3008',
    schemes: ['http'],
  };
  const outputfile = './swagger-output.json';
  const routes = ['D:/Video_block/New/Node/Project_setup/src/routes/userRoutes'];
  
  swaggerAutogen(outputfile,routes,doc);